import { Platform, Alert } from 'react-native';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';

export const shareSnapshot = async (snapshot, vehicle) => {
  if (!snapshot || !vehicle) return;

  const vehicleName = vehicle.nickname || `${vehicle.year} ${vehicle.make} ${vehicle.model}`;
  const date = new Date(snapshot.date).toLocaleDateString('en-US', { 
    month: 'long', 
    day: 'numeric', 
    year: 'numeric' 
  });

  const conditionEmojis = {
    excellent: '✨',
    good: '😊',
    fair: '😐',
    poor: '😞',
  };

  // Create a simple HTML snapshot card
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Car Story Snapshot — ${vehicleName}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { 
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
    background: #f8fafc; 
    padding: 20px;
    line-height: 1.5;
  }
  .card { 
    max-width: 400px; 
    margin: 20px auto; 
    background: white; 
    border-radius: 16px; 
    padding: 24px; 
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    border-left: 4px solid ${snapshot.condition === 'excellent' ? '#10B981' : 
                            snapshot.condition === 'good' ? '#3B82F6' :
                            snapshot.condition === 'fair' ? '#EAB308' : '#EF4444'};
  }
  .header { text-align: center; margin-bottom: 20px; }
  .emoji { font-size: 32px; margin-bottom: 8px; }
  .title { font-size: 20px; font-weight: 600; color: #1e293b; margin-bottom: 4px; }
  .vehicle { font-size: 14px; color: #64748b; margin-bottom: 16px; }
  .condition { 
    display: inline-block; 
    padding: 4px 12px; 
    border-radius: 12px; 
    font-size: 12px; 
    font-weight: 600; 
    text-transform: uppercase;
    background: ${snapshot.condition === 'excellent' ? '#dcfce7; color: #166534' : 
                 snapshot.condition === 'good' ? '#dbeafe; color: #1e40af' :
                 snapshot.condition === 'fair' ? '#fef3c7; color: #92400e' : '#fee2e2; color: #991b1b'};
    margin-bottom: 12px;
  }
  .details { margin-bottom: 16px; }
  .detail-row { display: flex; justify-content: space-between; margin-bottom: 8px; }
  .detail-label { color: #64748b; font-size: 14px; }
  .detail-value { color: #1e293b; font-weight: 500; font-size: 14px; }
  .notes { 
    background: #f1f5f9; 
    padding: 12px; 
    border-radius: 8px; 
    color: #475569; 
    font-size: 14px; 
    margin-top: 12px;
  }
  .footer { text-align: center; margin-top: 20px; padding-top: 16px; border-top: 1px solid #e2e8f0; }
  .footer-text { font-size: 12px; color: #94a3b8; }
</style>
</head>
<body>
  <div class="card">
    <div class="header">
      <div class="emoji">📸</div>
      <div class="title">${snapshot.title}</div>
      <div class="vehicle">${vehicleName}</div>
      <div class="condition">${snapshot.condition}</div>
    </div>
    
    <div class="details">
      <div class="detail-row">
        <span class="detail-label">Date</span>
        <span class="detail-value">${date}</span>
      </div>
      <div class="detail-row">
        <span class="detail-label">Odometer</span>
        <span class="detail-value">${snapshot.odometer?.toLocaleString() || '—'} miles</span>
      </div>
      ${snapshot.openIssuesCount > 0 ? `
      <div class="detail-row">
        <span class="detail-label">Open Issues</span>
        <span class="detail-value" style="color: #ef4444;">${snapshot.openIssuesCount}</span>
      </div>` : ''}
      ${snapshot.totalSpent > 0 ? `
      <div class="detail-row">
        <span class="detail-label">Total Spent</span>
        <span class="detail-value">$${snapshot.totalSpent.toFixed(2)}</span>
      </div>` : ''}
      ${snapshot.fuelEfficiency ? `
      <div class="detail-row">
        <span class="detail-label">Fuel Efficiency</span>
        <span class="detail-value">${snapshot.fuelEfficiency.toFixed(1)} MPG</span>
      </div>` : ''}
    </div>
    
    ${snapshot.notes ? `
    <div class="notes">
      ${snapshot.notes}
    </div>` : ''}
    
    <div class="footer">
      <div class="footer-text">Generated by Car Story</div>
    </div>
  </div>
</body>
</html>`;

  try {
    if (Platform.OS === 'web') {
      // Web: try to use Web Share API or open in new window
      if (navigator.share && navigator.canShare) {
        const shareData = {
          title: `${snapshot.title} — ${vehicleName}`,
          text: `Vehicle snapshot for ${vehicleName} on ${date}${snapshot.notes ? `: ${snapshot.notes}` : ''}`,
        };
        
        if (navigator.canShare(shareData)) {
          await navigator.share(shareData);
        } else {
          // Fallback to opening in new window
          const newWindow = window.open('', '_blank');
          if (newWindow) {
            newWindow.document.write(html);
            newWindow.document.close();
          }
        }
      } else {
        // Fallback to opening in new window
        const newWindow = window.open('', '_blank');
        if (newWindow) {
          newWindow.document.write(html);
          newWindow.document.close();
        }
      }
    } else {
      // Native: save HTML file and share
      const fileName = `CarStory_Snapshot_${vehicleName.replace(/\s+/g, '_')}_${date.replace(/\s+/g, '_')}.html`;
      const filePath = `${FileSystem.cacheDirectory}${fileName}`;
      
      await FileSystem.writeAsStringAsync(filePath, html, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(filePath, {
          mimeType: 'text/html',
          dialogTitle: `${snapshot.title} — ${vehicleName}`,
          UTI: 'public.html',
        });
      } else {
        Alert.alert('Sharing Unavailable', 'Unable to share on this device.');
      }
    }
  } catch (error) {
    console.error('Error sharing snapshot:', error);
    Alert.alert('Error', 'Failed to share snapshot. Please try again.');
  }
};

export default { shareSnapshot };